version: "3"
services:
  coursematerial:
    image: lauraleonilla/docker-course-1.15
    ports:
      - 3001:3001
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower