jobs:
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run: heroku container:login
orbs:
  heroku: circleci/heroku@0.0.10
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy