version: 2.0

machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

jobs:
  deployment:
    branch: master
    commands:
      - docker login --email=$DOCKER_LOGIN --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD registry.heroku.com
      - docker build --rm=false -t registry.heroku.com/chat-application-test-app/web .
      - docker push registry.heroku.com/chat-application-test-app/web:first
