version: 2.0

orbs:
  heroku: circleci/heroku@1.2.0

jobs:
  deploy:
    heroku:
      - run: heroku container:login
      - run: heroku create
      - run: heroku container:push web
      - run: heroku container:release web