version: 2.1

orbs:
  heroku: circleci/heroku@1.1.1

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: master