jobs:
  deploy:
    executor: heroku/default
    docker:
      - image: lauraleonilla/chat-app
    steps:
      - checkout
      - heroku/install
      - run: heroku container:login
      - run: heroku container:release web --app chat-application-test-app
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@0.0.10
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy