version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  deploy:
    docker:
      - image: lauraleonilla/chat-app:first
    steps:
      - checkout
      - run: heroku container:login
      - run: heroku create
      - run: heroku container:push web
      - run: heroku container:release web

workflows:
  deploy:
    jobs:
      - deploy