version: 2.1

jobs:
  build:
    docker:
      - image: lauraleonilla/chat-app:first
    steps:
      - checkout
      - run: docker-compose up
  deploy:
    docker:
      - image: lauraleonilla/chat-app:first
    steps:
      - checkout
      - run: heroku container:login
      - run: heroku create
      - run: heroku container:push web
      - run: heroku container:release web

workflows:
  build:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold