jobs:
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run: heroku container:login
      - run: heroku container:release web --app chat-application-test-app
orbs:
  heroku: circleci/heroku@0.0.10
  docker: circleci/docker@1.0.0
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy