version: 2.1

jobs:
  deploy:
    docker:
      - image: lauraleonilla/chat-app:first
    steps:
      - run: bash .circleci/setup-heroku.sh
      - run: heroku container:login
      - run: heroku create
      - run: heroku container:push web
      - run: heroku container:release web

workflows:
  deploy:
    jobs:
      - deploy